<?
$aMenuLinks = Array(
	Array(
		"Чехлы для телефона", 
		"/catalog/chekhly-dlya-telefonov/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Samsung", 
		"/catalog/chekhly-dlya-telefona-samsung/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Apple", 
		"/catalog/chekhly-dlya-telefonov-apple/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Huawei", 
		"/catalog/chekhly-dlya-telefona-huawei/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Xiaomi", 
		"/catalog/chekhly-dlya-telefona-xiaomi/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Для спорта", 
		"/catalog/sportivnye-chekhly-dlya-telefona/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Водонепроницаемые", 
		"/catalog/vodonepronitsaemye-chekhly-dlya-telefona/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>