<?$APPLICATION->IncludeComponent(
	"bitrix:search.title",
	"corp_custom",
	Array(
		"CATEGORY_0" => array("iblock_aspro_max_catalog"),
		"CATEGORY_0_TITLE" => "ALL",
		"CATEGORY_0_iblock_aspro_max_catalog" => array("all"),
		"CATEGORY_1" => array(),
		"CATEGORY_1_TITLE" => "",
		"CATEGORY_2" => array(),
		"CATEGORY_2_TITLE" => "",
		"CATEGORY_3" => array(),
		"CATEGORY_3_TITLE" => "",
		"CATEGORY_4" => array(),
		"CATEGORY_4_TITLE" => "",
		"CATEGORY_5" => array(),
		"CATEGORY_5_TITLE" => "",
		"CATEGORY_6" => array(),
		"CATEGORY_6_TITLE" => "",
		"CATEGORY_7" => array(),
		"CATEGORY_7_TITLE" => "",
		"CATEGORY_8" => array(),
		"CATEGORY_8_TITLE" => "",
		"CATEGORY_9" => array(),
		"CATEGORY_9_TITLE" => "",
		"CATEGORY_OTHERS_TITLE" => "OTHER",
		"CHECK_DATES" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CONTAINER_ID" => "title-search_fixed",
		"CONVERT_CURRENCY" => "N",
		"INPUT_ID" => "title-search-input_fixed",
		"NUM_CATEGORIES" => "20",
		"ORDER" => "rank",
		"PAGE" => CMax::GetFrontParametrValue("CATALOG_PAGE_URL"),
		"PREVIEW_HEIGHT" => "38",
		"PREVIEW_TRUNCATE_LEN" => "50",
		"PREVIEW_WIDTH" => "38",
		"PRICE_CODE" => array(0=>"BASE",),
		"PRICE_VAT_INCLUDE" => "Y",
		"SEARCH_ICON" => $arParams['SEARCH_ICON']=='Y'?'Y':'N',
		"SHOW_ANOUNCE" => "N",
		"SHOW_INPUT" => "Y",
		"SHOW_INPUT_FIXED" => "Y",
		"SHOW_OTHERS" => "Y",
		"SHOW_PREVIEW" => "Y",
		"TOP_COUNT" => "60",
		"USE_LANGUAGE_GUESS" => "Y"
	),
false,
Array(
	'ACTIVE_COMPONENT' => 'Y'
)
);?>